version: "2"

linters:
  disable:
    - errcheck
  enable:
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

  exclusions:
    rules:
      - path: test
        linters:
          - revive

  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
