version: "2"

linters:
  disable:
    - errcheck
  enable:
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

  exclusions:
    rules:
      - path: test
        linters:
          - revive

  settings:
    gosec:
      excludes:
        - G101 # Look for hard coded credentials
        - G305 # File traversal when extracting zip/tar archive
        - G306 # Poor file permissions used when writing to a new file

    revive:
      rules:
        - name: package-comments
          disabled: true
