apiVersion: build.dev/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: source-to-image
spec:
  buildSteps:
    - command:
        - /usr/local/bin/s2i
        - build
        - .
        - $(build.builder.image)
        - '--as-dockerfile'
        - /gen-source/Dockerfile.gen
      image: 'quay.io/openshift-pipeline/s2i:nightly'
      name: s2i-build-as-dockerfile
      volumeMounts:
        - mountPath: /gen-source
          name: gen-source
      workingDir: /workspace/source
    - args:
        - '--skip-tls-verify=true'
        - '--dockerfile=/gen-source/Dockerfile.gen'
        - '--context=/gen-source'
        - '--destination=$(build.output.image)'
      command:
        - /kaniko/executor
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      image: 'gcr.io/kaniko-project/executor:latest'
      name: step-build-and-push
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: false
      volumeMounts:
        - mountPath: /gen-source
          name: gen-source
      workingdir: /gen-source
