---
apiVersion: build.dev/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: buildpacks-v3
spec:
  buildSteps:
    - name: step-prepare
      image: docker.io/paketobuildpacks/builder:full
      securityContext:
        runAsUser: 0
        capabilities:
          add: ["CHOWN"]
      command:
        - /bin/bash
      args:
        - -c
        - >
          chown -R "1000:1000" "/workspace/source" &&
          chown -R "1000:1000" "/tekton/home"
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
    - name: step-detect
      image: docker.io/paketobuildpacks/builder:full
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/detector
      args:
        - -app=/workspace/source/$(build.source.contextDir)
        - -group=/layers/group.toml
        - -plan=/layers/plan.toml
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-restore
      image: docker.io/paketobuildpacks/builder:full
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/restorer
      args:
        - -layers=/layers
        - -cache-dir=/cache
        - -group=/layers/group.toml
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
    - name: step-build
      image: docker.io/paketobuildpacks/builder:full
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/builder
      args:
        - -app=/workspace/source/$(build.source.contextDir)
        - -layers=/layers
        - -group=/layers/group.toml
        - -plan=/layers/plan.toml
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-export
      image: docker.io/paketobuildpacks/builder:full
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/exporter
      args:
        - -app=/workspace/source/$(build.source.contextDir)
        - -layers=/layers
        - -cache-dir=/cache
        - -group=/layers/group.toml
        - $(build.output.image)
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
