# Copyright The Shipwright Contributors
#
# SPDX-License-Identifier: Apache-2.0

ARG BASE

FROM ${BASE}

RUN \
  dnf --assumeyes  --nodocs install tar && \
  dnf clean all && \
  rm -rf /var/cache/yum

USER 1000:1000
