= Installation

The Shipwright Build APIs and controllers can be installed directly with our release deployment, or with our operator.

##Prerequsites
Shipwright runs on top of https://kubernetes.io/[Kubernetes], and requires a cluster running version 1.21 or higher.

== Installing Shipwright Builds with the Operator

The Shipwright operator is designed to be installed with the https://olm.operatorframework.io/[Operator Lifecycle Manager] ("OLM").
Before installation, ensure that OLM has been deployed on your cluster by following the https://olm.operatorframework.io/docs/getting-started/#installing-olm-in-your-cluster[OLM installation instructions].

Once OLM has been deployed, use the following command to install the latest operator release from https://operatorhub.io/operator/shipwright-operator[operatorhub.io]:

[,sh]
----
$ oc apply -f https://operatorhub.io/install/shipwright-operator.yaml
----

== Usage

To deploy and manage https://github.com/shipwright-io/build[Shipwright Builds] in your cluster,
first make sure this operator is installed and running.

Next, create the following:

[,yaml]
----
---
apiVersion: operator.shipwright.io/v1alpha1
kind: ShipwrightBuild
metadata:
  name: shipwright-operator
spec:
  targetNamespace: shipwright-build
----

The operator will deploy Shipwright Builds in the provided `targetNamespace`.
When `.spec.targetNamespace` is not set, the namespace will default to `shipwright-build`.
Refer to the xref:docs/shipwrightbuild.adoc[ShipwrightBuild documentation] for more information about this custom resource.

##Installing Shipwright Builds Directly

We also publish a Kubernetes manifest that installs Shipwright directly into the `shipwright-build` namespace. Applying this manifest requires cluster administrator permissions:

[,sh]
----
$ oc apply -f https://github.com/shipwright-io/build/releases/download/v0.10.0/release.yaml
----

##Installing Sample Build Strategies

The Shipwright community maintains a curated set of build strategies for popular build tools. These can be optionally installed after Shipwright Builds has been deployed:

[,sh]
----
$ oc apply -f https://github.com/shipwright-io/build/releases/download/v0.10.0/sample-strategies.yaml
----
